2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Configure stats pid to 25460
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Loading settings from /home/minkukim/.config/wandb/settings
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Loading settings from /home/minkukim/workspace/dairlib/wandb/settings
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'bindings/pydairlib/perceptive_locomotion/perception_learning/inference/train_and_test.py', 'program_abspath': '/home/minkukim/workspace/dairlib/bindings/pydairlib/perceptive_locomotion/perception_learning/inference/train_and_test.py', 'program': '/home/minkukim/workspace/dairlib/bindings/pydairlib/perceptive_locomotion/perception_learning/inference/train_and_test.py'}
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_init.py:_log_setup():526] Logging user logs to /home/minkukim/workspace/dairlib/wandb/run-20240205_230436-r2p27s48/logs/debug.log
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_init.py:_log_setup():527] Logging internal logs to /home/minkukim/workspace/dairlib/wandb/run-20240205_230436-r2p27s48/logs/debug-internal.log
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_init.py:init():566] calling init triggers
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_init.py:init():616] starting backend
2024-02-05 23:04:36,177 INFO    MainThread:25460 [wandb_init.py:init():620] setting up manager
2024-02-05 23:04:36,179 INFO    MainThread:25460 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-05 23:04:36,180 INFO    MainThread:25460 [wandb_init.py:init():628] backend started and connected
2024-02-05 23:04:36,184 INFO    MainThread:25460 [wandb_init.py:init():720] updated telemetry
2024-02-05 23:04:36,187 INFO    MainThread:25460 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-05 23:04:36,553 ERROR   MainThread:25460 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-05 23:04:36,794 ERROR   MainThread:25460 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/minkukim/workspace/dairlib/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/minkukim/workspace/dairlib/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-05 23:04:37,819 WARNING MsgRouterThr:25460 [router.py:message_loop():77] message_loop has been closed
